### ISSUE TITLE
Scenarioテストでは、複数のエンドポイントを利用することは想定しないのですか？

### ISSUE THREAD

**Issue by developer-kikikaikai** [aimof/apitest#11]
yamlの定義としては1つなので1シナリオに対して1つのホストを指定する形に見えました。
そうなった場合、基本的にはこれで十分だと思うのですが、複数のサービスに跨って利用されるAPIの場合にどうテストするのでしょうか？

例えば認証前提のサービスAに対するAPIで、その認証情報はサービスBに対して登録されたものを使う場合、
1. サービスBに認証情報を登録して、
2. サービスAにアクセス

といった複数サービスを利用した試験をしたくなると思います。
こういった試験はカバーする設定があるのか、シナリオの定義でカバーするのか、そもそも対象外なのかが気になりました。

**Comment by aimof** [comment]
Translated by Google (for non-japanese speakers)
```
As it was one in the definition of yaml, it seemed to specify one host for one scenario.
In that case, I think that basically this is enough, but how do you test in the case of APIs that are used across multiple services?

For example, in the case of using the API for service A of authentication premise, the authentication information is the one registered for service B,

1. Register authentication information in service B,
2. Access service A
I would like to want to test using multiple services such as.
I was wondering if these tests had settings to cover, were covered by the scenario definition, or were not covered at all.
```

**Comment by aimof** [comment]
I'll update my [plan](https://github.com/aimof/apitest#plan)

Currently, I'll support testing only one repo so there are single target server and some mocks.
Now I cannot finish to develop mock server so it may be confuse to you.

1. __I only support single repo testing.__
2. __Other servers are all mocks.__

Is it the answer you wanted?

**Comment by developer-kikikaikai** [comment]
Yes, it's correct answer of my question.

**Comment by aimof** [comment]
Thanks to your question.
I'll update README and close this issue.

Thank you.
