### ISSUE TITLE
Dose this tool have a relation of docker-component version?

### ISSUE THREAD

**Issue by developer-kikikaikai** [aimof/apitest#12]
When I use test.sh in Ubuntu 18.04, there is a following error.
* Install docker-compose by apt command (I'm sorry to forget checking version).

```
$ ./test.sh
ERROR: Version in "././test/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

And I can run test.sh after updating dockrer-compose as following:

```
sudo apt remove docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

(Refer;https://stackoverflow.com/questions/42139982/version-in-docker-compose-yml-is-unsupported-you-might-be-seeing-this-error)

So,  this tool need some minimum version of docker-component. Doesn't it?

**Comment by aimof** [comment]
Please see [docker-compose.yml version](https://github.com/aimof/apitest/blob/0df2b35ee28140799ee6dbbc9bfd871ef080e191/test/docker-compose.yml#L1)
It's 3.7.

Let's see [docker document](https://docs.docker.com/compose/compose-file/compose-versioning/).

version 3.7 needs 18.06.0+

I'll Update READEME and close this issue.
